[package]
name = "spam-block-reqs"
version = "1.0.0"
edition = "2021"
author = "Andrew Toth"
license = "MIT"

[dependencies]
anyhow = "1.0"
bitcoin = { version = "0.29.2", features = ["rand"] }
log = "0.4.17"
env_logger = "0.10.0"
clap = { version = "4.0.29", features = ["derive"] }
